
# MongoDB Configuration
# Note: The database name is included at the end of the URI
spring.mongodb.uri=mongodb://localhost:27017/fitnessactivity

#kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer   

kafka.topic.name=actvity-events

# Server Port
server.port=8082

# Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# FIX: Explicitly forces localhost to bypass the Windows mshome.net network bug
eureka.instance.hostname=localhost

# Optional: Enable Debug logging to see the connection details
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
